@startuml Package Diagram

package "src" {
    package "app" as App {
        [Layout Wrappers]
        [Screens]
    }

    package " " as Components {
      
    }

    package "lib" {
        package "context" as Context {
            package "Auth"
            package "Notes"
            package "Weather"
        }

        package "services" as Services {
            [Todoist API]
        }
        
        package "axios" as Network {
            [HTTP Clients]
        }
        
        package "db" as Database {
            [Local DB Config]
        }
    }
}

App ..> Components : imports
App ..> Context : consumes state

Components ..> Context

Context ..> Services : fetches data
Context ..> Database : persists data

Services ..> Network : uses axios instance

@enduml