@startuml Use Case Diagram
left to right direction
skinparam packageStyle rectangle

actor "User" as user
actor "Todoist API" as todoist
actor "Weather API" as weather

rectangle "Tick it" {
    usecase "Authenticate with\nbiometrics to use app" as UC03
    usecase "View Notes" as UC04
    usecase "Create Note" as UC05
    usecase "Edit Note" as UC06
    usecase "Delete Note" as UC07
    usecase "Log into Todoist" as UC01
    usecase "Log out" as UC02
    usecase "View Weather" as UC08
    usecase "Sync Data" as UC09
}

user --> UC01
user --> UC02
user --> UC03
user --> UC04
user --> UC05
user --> UC06
user --> UC07
user --> UC08

UC05 ..> UC09 : <<include>> \n(when online)
UC06 ..> UC09 : <<include>> \n(when online)
UC07 ..> UC09 : <<include>> \n(when online)

UC01 <-- todoist : Authenticates User
UC08 <--- weather : Fetches Weather Info
UC09 <-- todoist : Syncs Notes

@enduml